-- https://programmers.co.kr/learn/courses/30/lessons/59045
SELECT a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
    FROM ANIMAL_INS a INNER JOIN ANIMAL_OUTS b
    ON (a.ANIMAL_ID = b.ANIMAL_ID AND a.SEX_UPON_INTAKE != b.SEX_UPON_OUTCOME)
    ORDER BY ANIMAL_ID;
          
-- solution 2
/*SELECT ANIMAL_ID, ANIMAL_TYPE, NAME FROM ANIMAL_INS a
    WHERE ANIMAL_ID IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS b
        WHERE b.SEX_UPON_OUTCOME NOT LIKE 'Intact%')
        AND SEX_UPON_INTAKE LIKE 'Intact%' ORDER BY ANIMAL_ID;*/
