-- TBL_LT_HIS의 PK (FA_ID, LT_ID, PROD_ID, TIMEKEY)

-- PK중복이 없는 TEST01의 데이터 확인 (190000개 행 중 189000개 출력)
SELECT COUNT(*) FROM TEST01.TBL_LT_HIS a
    WHERE NOT EXISTS (SELECT b.* FROM TEST02.TBL_LT_HIS b
    WHERE (a.FA_ID = b.FA_ID
    AND a.LT_ID = b.LT_ID
    AND a.PROD_ID = b.PROD_ID
    AND a.TIMEKEY = b.TIMEKEY));

-- PK중복이 없는 TEST02의 데이터 확인(196000개 행 중 195000개 출력)
SELECT COUNT(*) FROM TEST02.TBL_LT_HIS b
    WHERE NOT EXISTS (SELECT a.* FROM TEST01.TBL_LT_HIS a
    WHERE (a.FA_ID = b.FA_ID
    AND a.LT_ID = b.LT_ID
    AND a.PROD_ID = b.PROD_ID
    AND a.TIMEKEY = b.TIMEKEY));

INSERT INTO TEST03.TBL_LT_HIS c
    (SELECT CASE FA_ID
        WHEN 'F12' THEN 'F11' ELSE a.FA_ID END,
        LT_ID, PROD_ID, PROD_DESC, FL_ID, FL_DESC, OP_ID, OP_DESC, EVENT_DESC, USER_ID
        FROM TEST01.TBL_LT_HIS a
        WHERE NOT EXISTS (SELECT b.* FROM TEST02.TBL_LT_HIS b
        WHERE (a.FA_ID = b.FA_ID
        AND a.LT_ID = b.LT_ID
        AND a.PROD_ID = b.PROD_ID))
    )
    UNION ALL
    (SELECT CASE FA_ID
        WHEN 'F12' THEN 'F11' ELSE b.FA_ID END, 
        LT_ID, PROD_ID, PROD_DESC, FL_ID, FL_DESC, OP_ID, OP_DESC, EVENT_DESC, USER_ID
        FROM TEST02.TBL_LT_HIS b
        WHERE NOT EXISTS (SELECT a.* FROM TEST01.TBL_LT_HIS a
        WHERE (a.FA_ID = b.FA_ID
        AND a.LT_ID = b.LT_ID
        AND a.PROD_ID = b.PROD_ID))
    )
    UNION ALL
    (SELECT a.* FROM TEST01.TBL_LT_HIS a, TEST02.TBL_LT_HIS b
        WHERE (a.FA_ID = b.FA_ID
        AND a.LT_ID = b.LT_ID
        AND a.PROD_ID = b.PROD_ID)
    );