-- https://programmers.co.kr/learn/courses/30/lessons/59044
SELECT NAME, DATETIME FROM (
    SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS a
        WHERE NOT EXISTS (SELECT * FROM ANIMAL_OUTS b
            WHERE a.ANIMAL_ID = b.ANIMAL_ID) ORDER BY DATETIME
) WHERE ROWNUM <= 3;
